swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
      
  /transactions:
    get:
      tags:
        - Transactions
      summary: Transactions du mois en cours groupées par compte
      description: Retourne les détails de toutes les transactions pour le mois en cours, organisées par compte utilisateur.
      parameters:
        - name: month
          in: query
          description: Mois pour lequel récupérer les transactions
          required: true
          operationId: transactionsbymonth
          explode: true
          schema:
            type: string
            enum:
              - janvier
              - fevrier
      responses:
        '200':
          description: Succès de la requête. Les transactions groupées.
          schema:
            content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/'
        '400':
          description: Aucune élément trouvé 
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Obtenir les détails d'une transaction spécifique
      description: Retourne les détails d'une transaction spécifique identifiée par transactionId.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: integer
          description: ID de la transaction à récupérer
      responses:
        '200':
          description: Succès de la requête. Retourne les détails de la transaction demandée.
          schema:
            content:
            application/json:
              schema:
                $ref: '#/components/'
        '404':
          description: La transaction spécifiée n'a pas été trouvée.
    put:
      tags:
        - Transactions
      summary: Mettre à jour les détails d'une transaction spécifique
      description: Met à jour les informations d'une transaction spécifique identifiée par transactionId.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID de la transaction à mettre à jour
        - in: body
          name: body
          required: true
          description: Nouveau valeur
          schema:
            type: string
      responses:
        '200':
          description: Succès de la requête. Retourne les détails mis à jour de la transaction.
          schema:
            type: object 
        '404':
          description: La transaction spécifiée n'a pas été trouvée.
    delete:
      tags:
        - Transactions
      summary: Supprimer une infomation sur une transaction spécifique 
      description: Supprime une transaction spécifique identifiée par transactionId.
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID de la transaction à supprimer
      responses:
        '200':
          description: Succès de la requête. La transaction a été supprimée avec succès.
        '404':
          description: La transaction spécifiée n'a pas été trouvée.

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
        
      